Update test result file name

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -21,4 +21,9 @@ jobs:
       - name: Install the project dependencies
         run: poetry install
       - name: Run tests
-        run: poetry run pytest --junitxml=junit.xml --cov-report=xml --cov-report=html
+        run: poetry run pytest --junitxml=pytest-junit.xml --cov-report=xml --cov-report=html
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'pytest-junit.xml'
